In [2]:
import numpy as np

In [3]:
np.array(1)

array(1)

In [4]:
list = [1, 2, 4, 6]
a = np.array(list)

In [5]:
a.max()

6

In [6]:
a[:2]

array([1, 2])

In [10]:
b = a[0 : 1]
b

array([1])

In [11]:
b[:] = 10

In [12]:
a

array([10,  2,  4,  6])