In [2]:
import numpy as np

In [3]:
#np.reshape()
#np.array()

In [10]:
mydata = np.arange(0, 20)

In [11]:
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
np.reshape(mydata, (5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
a = np.reshape(mydata, (5, 4), order='C')

In [16]:
a[2, 2]

10

In [17]:
b = np.reshape(mydata, (5, 4), order='F')

In [18]:
b

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [19]:
c = mydata.reshape(5, 4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [20]:
r1 = [1, 2, 3]
r2 = [4, 5, 6]
d = np.array([r1, r2])
d

array([[1, 2, 3],
       [4, 5, 6]])